#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.legendarymonuments]
			distortion = true

		[types.wood_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.beachparty]
			palm = true

		[types.wood_type.cluttered]
			willow = true
			flowering_willow = true
			poplar = true
			flowering_poplar = true
			crabapple = true
			flowering_crabapple = true
			sycamore = true
			fluorescent_maple = true
			blue_mushroom = true
			red_mushroom = true

		[types.leaves_type.mcwholidays]
			yellow_oak = true
			orange_oak = true
			red_oak = true
			brown_oak = true
			mixed_oak = true
			snowy_oak = true
			snowy_spruce = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_apple_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_apple_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_apple_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_apple_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_apple_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_apple_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true

		[types.leaves_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.leaves_type.twilightforest]
			thorn = true
			beanstalk = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.beachparty]
			palm = true

		[types.leaves_type.cluttered]
			willow = true
			flowering_willow = true
			poplar = true
			flowering_poplar = true
			crabapple = true
			flowering_crabapple = true
			sycamore = true
			fluorescent_maple = true
			flowering_fluorescent_maple = true

		[types.leaves_type.twilightdelight]
			ironwood = true

#Disables specific entries
[entries]

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			tiled_door = true
			center_cut_log = true
			pegged_planks = true
			secret_door = true
			smooth_planks = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			edged_stripped_log = true
			beach_door = true
			fine_vertical_planks = true
			diamond_bordered_glass = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			firewood_log = true
			f_sign_stripped_log = true
			layered_stripped_log = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			mixed_log = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			detailed_planks = true
			cobweb_trapdoor = true
			barred_trapdoor = true
			airy_trapdoor = true
			patient_stripped_log = true
			pressed_door = true
			planks_panel = true
			solid_trapdoor = true
			boarded_door = true
			meshed_trapdoor = true
			fancy_trapdoor = true
			paper_door = true
			basket_woven_planks = true
			enclosed_planks = true
			flowering_log = true
			k_sign_stripped_log = true
			double_herringbone_planks = true
			sign_stripped_log = true
			crated_planks = true
			knotted_stripped_log = true
			reinforced_log = true
			classic_windowed_trapdoor = true
			wickered_planks = true
			heavy_trapdoor = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			bundled_log = true
			polished_planks = true
			ornate_bared_glass_pane = true
			stern_stripped_log = true
			wall_torch = true
			glass_door = true
			paneled_door = true
			leafy_trapdoor = true
			pointless_trapdoor = true
			planks_shavings = true
			d_sign_stripped_log = true
			windowed_trapdoor = true
			tile_windowed_door = true
			golden_barred_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			classic_trapdoor = true
			circle_glass = true
			torch = true
			screen_door = true
			crossed_planks = true
			cross_laced_planks = true
			railed_planks = true
			planks_mosaic = true
			circle_glass_pane = true
			versailles_planks = true
			wise_stripped_log = true
			planked_log = true
			woven_glass = true
			woven_trapdoor = true
			gated_door = true
			supported_door = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			lumpy_stripped_log = true
			line_bared_glass = true
			slanted_planks = true
			edge_cut_log = true
			barred_door = true
			chipped_stripped_log = true
			suspicious_trapdoor = true
			herringbone_planks = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			tiled_planks = true
			dual_paneled_door = true
			square_glass_pane = true
			overgrown_log = true
			thin_planks = true
			warted_trapdoor = true
			horizontal_lined_glass = true
			l_sign_stripped_log = true
			natural_planks = true
			brick_bond_planks = true
			bordered_glass_pane = true
			sliding_door = true
			bordered_glass = true
			reinforced_stripped_log = true
			shack_door = true
			diagonal_planks = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			fortified_door = true
			carved_stripped_log = true
			snowflake_glass = true
			heavy_door = true
			stacked_planks = true
			i_sign_stripped_log = true
			twisted_trapdoor = true
			diamond_planks = true
			woven_glass_pane = true
			damaged_log = true
			nailed_log = true

		[entries.wood_type.mcwroofs]
			top_roof = true
			lower_roof = true
			planks_roof = true
			steep_roof = true
			planks_top_roof = true
			planks_upper_steep_roof = true
			upper_steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			roof = true
			planks_attic_roof = true
			planks_steep_roof = true
			planks_lower_roof = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			stripped_double_kitchen_cabinet = true
			end_table = true
			stool_chair = true
			stripped_kitchen_sink = true
			stripped_drawer_counter = true
			stripped_counter = true
			covered_desk = true
			stripped_modern_wardrobe = true
			stripped_covered_desk = true
			stripped_kitchen_cabinet = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			striped_chair = true
			stripped_large_drawer = true
			wardrobe = true
			kitchen_sink = true
			modern_desk = true
			stripped_end_table = true
			drawer = true
			stripped_glass_kitchen_cabinet = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			kitchen_cabinet = true
			counter = true
			table = true
			stripped_double_drawer = true
			lower_triple_drawer = true
			glass_kitchen_cabinet = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			stripped_desk = true
			stripped_lower_triple_drawer = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_striped_chair = true
			stripped_stool_chair = true
			cupboard_counter = true
			coffee_table = true
			glass_table = true
			stripped_double_drawer_counter = true
			lower_bookshelf_drawer = true
			double_kitchen_cabinet = true
			stripped_lower_bookshelf_drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			desk = true
			stripped_double_wardrobe = true
			triple_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.handcrafted]
			fancy_bed = true
			dining_bench = true
			drawer = true
			couch = true
			bench = true
			counter = true
			corner_trim = true
			desk = true
			side_table = true
			table = true
			chair = true
			shelf = true
			cupboard = true
			pillar_trim = true
			nightstand = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			waffle_door = true
			cottage_door = true
			swamp_door = true
			barn_door = true
			classic_door = true
			beach_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			glass_door = true
			mystic_door = true
			whispering_door = true
			bark_glass_door = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			log_bridge_stair = true
			rope_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.mcwtrpdoors]
			swamp_trapdoor = true
			cottage_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			barred_trapdoor = true
			ranch_trapdoor = true
			beach_trapdoor = true
			glass_trapdoor = true
			whispering_trapdoor = true
			blossom_trapdoor = true
			tropical_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			mystic_trapdoor = true
			barrel_trapdoor = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.mcwwindows]
			plank_four_window = true
			window2 = true
			stripped_log_window = true
			plank_window2 = true
			louvered_shutter = true
			plank_pane_window = true
			stripped_log_window2 = true
			log_parapet = true
			stripped_log_four_window = true
			plank_window = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.wood_type.twilightforest]
			hollow_log_climbable = true
			banister = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

		[entries.wood_type.mcwfences]
			picket_fence = true
			wired_fence = true
			pyramid_gate = true
			highley_gate = true
			stockade_fence = true
			horse_fence = true

		[entries.wood_type.beautify]
			picture_frame = true
			blinds = true
			trellis = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.mighty_mail]
			mail_box = true

		[entries.wood_type.mcwlights]
			soul_tiki_torch = true
			ceiling_fan_light = true
			tiki_torch = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.leaves_type.chipped]
			frosted_leaves = true
			orange_leaves = true
			red_leaves = true
			magenta_flower_leaves = true
			cherry_leaves = true
			golden_cherry_leaves = true
			golden_leaves = true
			dead_leaves = true
			apple_leaves = true
			golden_apple_leaves = true
			white_flower_leaves = true

		[entries.leaves_type.mcwfences]
			hedge = true
